version: "3.4"
services:
  node-exporter:
    build:
      context: node_exporter
      args:
        NODE_EXPORTER_UPSTREAM_VERSION: v1.5.0
    restart: always
    volumes:
      - "/proc:/host/proc:ro"
      - "/sys:/host/sys:ro"
    image: "node-exporter.dappnode-exporter.dnp.dappnode.eth:1.0.1"
  cadvisor:
    build:
      context: cadvisor
      args:
        CADVISOR_UPSTREAM_VERSION: v0.47.1
    restart: always
    volumes:
      - "/:/rootfs:ro"
      - "/var/run:/var/run:rw"
      - "/sys:/sys:ro"
      - "/var/lib/docker/:/var/lib/docker:ro"
    image: "cadvisor.dappnode-exporter.dnp.dappnode.eth:1.0.1"
