version: "3.4"
services:
  node-exporter:
    build:
      context: node_exporter
      args:
        NODE_EXPORTER_UPSTREAM_VERSION: v1.6.1
    restart: always
    volumes:
      - "/:/host:ro,rslave"
    command:
      - "--path.rootfs=/host"
    image: "node-exporter.dappnode-exporter.dnp.dappnode.eth:1.0.3"
  cadvisor:
    build:
      context: cadvisor
      args:
        UPSTREAM_VERSION: v0.47.1
    restart: always
    volumes:
      - "/:/rootfs:ro"
      - "/var/run:/var/run:rw"
      - "/sys:/sys:ro"
      - "/var/lib/docker/:/var/lib/docker:ro"
    image: "cadvisor.dappnode-exporter.dnp.dappnode.eth:1.0.3"
  stakers-metrics:
    build:
      context: stakers-metrics
      dockerfile: Dockerfile
    restart: always
    image: "stakers-metrics.dappnode-exporter.dnp.dappnode.eth:1.0.3"
    environment:
      - DEBUG_MODE=false
