{
 "title": "Docker",
 "description": "DAppNodePackages Metrics",
 "tags": [
  "docker",
  "DAppNodeCore"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "2h",
 "templating": {
  "list": [
   { "name": "PackageType", "label": "Type", "query": "DAppNodeCore,DAppNodePackage" },
   { "name": "PackageName", "label": "Name", "query": "container_last_seen" }
  ]
 },
 "panels": [
  {
   "title": "CPU Load",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "100 - (avg by (instance) (irate(node_cpu_seconds_total{mode=\"idle\"}[5m])) * 100)"
    }
   ]
  },
  {
   "title": "CPU Cores",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "machine_cpu_cores" }
   ]
  },
  {
   "title": "Memory Load",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 0 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "(sum(node_memory_MemTotal_bytes) - sum(node_memory_MemFree_bytes+node_memory_Buffers_bytes+node_memory_Cached_bytes) ) / sum(node_memory_MemTotal_bytes) * 100"
    }
   ]
  },
  {
   "title": "Used Memory",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 0 },
   "format": "bytes",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{image!=\"\"}-container_memory_cache{image!=\"\"})"
    }
   ]
  },
  {
   "title": "System Storage Load",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(node_filesystem_size_bytes{mountpoint=\"/\"} - node_filesystem_free_bytes{mountpoint=\"/\"}) / node_filesystem_size_bytes{mountpoint=\"/\"}  * 100"
    }
   ]
  },
  {
   "title": "Used Storage",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 0 },
   "format": "bytes",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(container_fs_usage_bytes{device=~\"/dev/.*\",})"
    }
   ]
  },
  {
   "title": "Running DAppNodePackages",
   "type": "graph",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "scalar(count(container_memory_usage_bytes{image!=\"\",container_label_org_label_schema_group=\"\",name=~\"$PackageType.*\", container_label_com_docker_compose_service=~\"$PackageName\"}) > 0)",
     "legendFormat": "containers"
    }
   ]
  },
  {
   "title": "System Load",
   "type": "graph",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "node_load1", "legendFormat": "load 1m" }
   ]
  },
  {
   "title": "I/O Usage",
   "type": "graph",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 4 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(irate(node_disk_read_bytes_total[5m]))",
     "legendFormat": "read"
    },
    {
     "expr": "sum(irate(node_disk_written_bytes_total[5m]))",
     "legendFormat": "written"
    },
    {
     "expr": "sum(irate(node_disk_io_time_seconds_total[5m]))",
     "legendFormat": "io time"
    }
   ]
  },
  {
   "title": "DAppNodePackage CPU Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum by (container_label_com_docker_compose_service) (rate(container_cpu_usage_seconds_total{image!=\"\",container_label_org_label_schema_group=\"\",name=~\"$PackageType\", container_label_com_docker_compose_service=~\"$PackageName\"}[1m])) / scalar(count(node_cpu_seconds_total{mode=\"user\"})) * 100",
     "legendFormat": "{{ container_label_com_docker_compose_service }}"
    }
   ]
  },
  {
   "title": "DAppNodePackage Memory Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": " sum by (container_label_com_docker_compose_service)(container_memory_usage_bytes{image!=\"\",container_label_org_label_schema_group=\"\",name=~\"$PackageType.*\", container_label_com_docker_compose_service=~\"$PackageName\"}-container_memory_cache{image!=\"\",container_label_org_label_schema_group=\"\",name=~\"$PackageType.*\", container_label_com_docker_compose_service=~\"$PackageName\"})",
     "legendFormat": "{{ container_label_com_docker_compose_service }}"
    }
   ]
  },
  {
   "title": "DAppNodePackage Cached Memory Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum by (container_label_com_docker_compose_service) (container_memory_cache{image!=\"\",container_label_org_label_schema_group=\"\",name=~\"$PackageType.*\", container_label_com_docker_compose_service=~\"$PackageName\"})",
     "legendFormat": "{{container_label_com_docker_compose_service}}"
    }
   ]
  },
  {
   "title": "DAppNodePacakge Network Input",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum by (container_label_com_docker_compose_service) (rate(container_network_receive_bytes_total{image!=\"\",container_label_org_label_schema_group=\"\",name=~\"$PackageType.*\", container_label_com_docker_compose_service=~\"$PackageName\"}[1m]))",
     "legendFormat": "{{ container_label_com_docker_compose_service }}"
    }
   ]
  },
  {
   "title": "DAppNodePackage Network Output",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum by (container_label_com_docker_compose_service) (rate(container_network_transmit_bytes_total{image!=\"\",container_label_org_label_schema_group=\"\",name=~\"$PackageType.*\", container_label_com_docker_compose_service=~\"$PackageName\"}[1m]))",
     "legendFormat": "{{ container_label_com_docker_compose_service }}"
    }
   ]
  }
 ]
}